# inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'public/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 3.0
  SuggestExtensions: false
